name: Build and push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get current rust app version from its Cargo.toml.
        id: cargo
        uses: dante-signal31/rust-app-version@v1.2.0
        with:
          cargo_toml_folder: hulykvs_server/

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: hulykvs_server/Dockerfile
          push: true
          tags: "ghcr.io/aav/hulykvs:${{ steps.cargo.outputs.app_version }}"


